name = Organic Group
description = Layout for a group's pages
preview = preview.png
template = og-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/og/og.layout.css
stylesheets[all][] = css/layouts/og/og.layout.no-query.css