name = Everywhere
description = Layout for panels everywhere site template
preview = preview.png
template = everywhere-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/everywhere/everywhere.layout.css
stylesheets[all][] = css/layouts/everywhere/everywhere.layout.no-query.css